### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by hambone01** [arm64-compat/confluent-platform#11]
Hello,
  Please forgive me if raising an Issue isn't the right approach to both, thank you guys, and then beg for help.

I would love to use this repo to build kafka/zookeeper images I can use on my M1. However, I am not certain if I can since I don't use the confluent platform. Should I be able to build the images to my local docker repo and then use them in my very non-confluent Docker Desktop Kubernetes cluster?

Maybe I could provide back some general instructions in MD?

Good luck and thanks for your work.

sg

**Comment by altaiezior** [comment]
Hello, @hambone01 not sure if I understand the question correctly. But I will try my best to answer this.

So as far as I understand, kafka by itself doesn't have an official image on docker hub.

Kafka is being currently maintained by Apache as well as Confluent.

Confluent provides more enterprise grade solution around kafka, like schema registry, ksql etc.

Apache by itself doesn't have it's kafka image on docker hub. Prominent choices as what I have used are

Confluent kafka images and https://hub.docker.com/r/wurstmeister/kafka/

The same goes for Zookeeper as well.

Before version 7.2 kafka didn't provide ARM compatible images which was a pain point for most of the developers who uses Mac M1 laptops as amd images really takes a lot of time to come up, build and even makes M1 mac cry in terms of performance.

Hence I initiated this open source organisation which adds to it's portfolio some prominent images which we use on daily basis but doesn't have official ARM compatible version available. Sometimes it is just a matter of rebuilding the code on an ARM64 system. But due to lack of availability of ARM systems in CI / CD pipelines a lot of good projects also don't have arm compatible images.

The repo uses circleci to build both amd64 / arm64 compatible images and makes it available

https://github.com/orgs/arm64-compat/packages?repo_name=confluent-platform

So if you are just interested in using the images you don't have to through the entire build process as it will obviously eat up your 3-4 hours for sure.

If you want to use the versions > 7.2 then I would recommend going for official confluent images https://hub.docker.com/r/confluentinc/cp-server
https://hub.docker.com/r/confluentinc/cp-zookeeper

They are arm compatible as well, if you wish to use for version < 7.2 then this repo would help.

For building purpose you can refer to the MD file or the circleci config to get more details on your local system. Don't forget to pull the sub modules.

You can close the issue if this answers your question.
